spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://localhost:9411/
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
  config:
    import: "optional:configserver:"

server:
  port: 9001

