server:
  port: 9002

spring:
  application:
      name: USER-SERVICE
  zipkin:
    base-url: http://localhost:9411/
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
  config:
    import: "optional:configserver:"
